### ISSUE TITLE
Can't run

### ISSUE THREAD

**Issue by alex-makarov** [rozik/transportation#1]
==> default: Mounting shared folders...
...
Failed to mount folders in Linux guest. This is usually because
the "vboxsf" file system is not available. Please verify that
the guest additions are properly installed in the guest and
can work properly. The command attempted was:

mount -t vboxsf -o uid=`id -u vagrant`,gid=`getent group vagrant | cut -d: -f3` vagrant /vagrant
mount -t vboxsf -o uid=`id -u vagrant`,gid=`id -g vagrant` vagrant /vagrant

The error output from the last command was:

stdin: is not a tty
mount: unknown filesystem type 'vboxsf'

**Comment by rozik** [comment]
Hallo Alex,

please, get the latest version and try it again.


Mit freundlichen Grüßen,
Alexander Rosenberg
